name: tugas_akhir
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  url_launcher: ^6.1.14
  qr_flutter: ^4.1.0
  webview_flutter: ^4.2.4
  midtrans_sdk: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_rm.png
    - assets/menus/rendang.png
    - assets/menus/gulai_tunjang.png
    - assets/menus/ayam_goreng.png
    - assets/menus/dendeng_balado.png
    - assets/menus/telur_barendo.png
    - assets/menus/gulai_tambusu.png
    - assets/menus/kalio_jariang.png
    - assets/menus/udang_balado.png
    - assets/menus/jangek_siram.png
    - assets/menus/ikan_bakar.png
    - assets/menus/telur_bulat_balado.png
    - assets/bank.png
    - assets/cod.png
    
